title: mu-open
hero_image: images/banner.png
description: mu-open description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-29"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
